name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Cache build output
        uses: actions/cache@v4
        with:
          path: ./dist
          key: ${{ runner.os }}-web-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-web-

      - name: Build project
        run: bun run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: trash-collector
          directory: ./dist
